### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by lugard1** [SSEKPIUS/Microverse-Awesome-books#5]
- [ ] clean code.
- [ ] Good workflow.
- [ ] Good job done! The code looks neat and clean. Just a few recommendations.
 https://github.com/SSEKPIUS/Microverse-Awesome-books/blob/557733386aba6f66456a3d8b688f820e83261264/index.js#L17 
- [ ] I suggest that your variable names should be a bit more descriptive.

**Comment by jodavid444** [comment]
you have done a great job so far keep it up
